name: Apple Binaries

on:
  workflow_dispatch:

jobs:
  linking:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Tolgee CLI
        run: npm install --global @tolgee/cli

      - name: Install tree
        run: brew install tree

      - name: Install Cocoapods
        run: brew install cocoapods

      - name: Build
        run: ./gradlew core:build

      - name: Framework Tolgee
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeXCFramework || ./gradlew core:assembleXCFramework

      - name: Framework Tolgee Release
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeReleaseXCFramework || ./gradlew core:assembleReleaseXCFramework

      - name: Framework Tolgee Debug
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeDebugXCFramework || ./gradlew core:assembleDebugXCFramework

      - name: Folder Structure
        run: tree core/build

      - name: Upload core build directory
        uses: actions/upload-artifact@v4
        with:
          path: core/build